context:
  version: "14.8.4"

package:
  name: textlint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/textlint/-/textlint-${{ version }}.tgz
  sha256: 7e5f9eb2b306bebc1f07d53c8dc3573c906acb944b8ebdf0bb2c92e26586967c

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - textlint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The pluggable natural language linter for text and markdown
  homepage: https://github.com/textlint/textlint
  repository: https://github.com/textlint/textlint

extra:
  recipe-maintainers:
    - danielnachun
