context:
  version: "14.4.2"

package:
  name: textlint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/textlint/-/textlint-${{ version }}.tgz
  sha256: 88797d8c0cb53dc8883ba478441da1cda1aa5ef38a2cc75af0d2a8ffcaf56eff

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - textlint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The pluggable natural language linter for text and markdown
  homepage: https://github.com/textlint/textlint
  repository: https://github.com/textlint/textlint

extra:
  recipe-maintainers:
    - danielnachun
