context:
  version: "15.5.4"

package:
  name: textlint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/textlint/-/textlint-${{ version }}.tgz
  sha256: 5c85efc119d23b87aea909fc51522e34b9c20dedcebdb879a92088d7bc81b5e7

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - textlint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The pluggable natural language linter for text and markdown
  homepage: https://github.com/textlint/textlint
  repository: https://github.com/textlint/textlint

extra:
  recipe-maintainers:
    - danielnachun
