context:
  version: "15.8.0"

package:
  name: textlint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/textlint/-/textlint-${{ version }}.tgz
  sha256: 244be062653dd1b2ebaca1a7d6906f838e11e8635d3b624b46ba6605dcc15bef

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - textlint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The pluggable natural language linter for text and markdown
  homepage: https://github.com/textlint/textlint
  repository: https://github.com/textlint/textlint

extra:
  recipe-maintainers:
    - danielnachun
