context:
  version: "15.7.1"

package:
  name: textlint
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/textlint/-/textlint-${{ version }}.tgz
  sha256: 24814002726642b9ef91b97b7eddbcbb7f9766397a60d94b6dcfa02ef76e73f0

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - textlint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The pluggable natural language linter for text and markdown
  homepage: https://github.com/textlint/textlint
  repository: https://github.com/textlint/textlint

extra:
  recipe-maintainers:
    - danielnachun
